# Generated by Django 3.0.4 on 2020-03-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LimitCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_db', models.TextField(default='NA')),
                ('timestamp_db', models.TextField(default='NA')),
                ('occurence_db', models.TextField(default='NA')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_db', models.TextField(default='NA')),
                ('email_db', models.TextField(default='NA')),
                ('password_db', models.TextField(default='NA')),
                ('ip_db', models.TextField(default='NA')),
            ],
        ),
    ]
